#%RAML 1.0 DataType
displayName: Account
description: Defines the fields in Account DataType

type: object
properties:
  ID?: string 
  AccountNumber?: string
  Description?: string
  Name?: string
  NumberOfEmployees?: string 
  LastModifiedDate?: datetime
  Type?: string