#%RAML 1.0 DataType
displayName: Contact
description: Defines the fields in Contact Datatype

type: object
properties:
  ID?: integer 
  Email?: string
  FirstName?: string
  LastName?: string
  Description?: string
  Phone?: string 
  LastModifiedDate?: datetime