#%RAML 1.0 NamedExample

value:
-
  Id/: "123"
  AccountNumber?: "DD89TE"
  Name?: "John"
  Description?: "Testing tools by John"
  NumberOfEmployees?: "100"
  LastModifiedDate?: 2019-08-21T04:34:41.098Z
  Type?: "Customer - direct"
-
  Id?: "178"
  AccountNumber?: "PP78TE"
  Name?: "Mike"
  Description?: " John"
  NumberOfEmployees?: "50"
  LastModifiedDate?: 2019-08-21T04:34:41.098Z
  Type?: "Customer - Channel"


 