#%RAML 1.0 NamedExample
value:
-
  Id?: "100"
  Name?: "Sean Forbes"
  Email?: "sean@edge.com"
  type?: "contact"
  Phone?: "1234567"
  Description?: "Player"
  LastModifiedDate?: 2019-08-21T04:34:41.098Z
-
  Id?: "101"
  Name?: "Jack Rogers"
  Email?: "jack@gmail.com"
  type?: "Contact"
  Phone?: "9876543"
  Description?: "programmer"
  LastModifiedDate?: 2019-08-21T04:34:41.098Z
