#%RAML 1.0 NamedExample

value:
-
  Id?: 100
  Name?: "John"
  Description?: "player"
  NumberOfEmployees?: 50
  Type?: "Customer-Direct"
  AccountNumber?: "AA11TE"
-
  Id?: 101
  Name?: "Mike"
  Description?: "programmer"
  NumberOfEmployees?: 100
  Type?: "Customer-Channel"
  AccountNumber?: "BB12TE"
