#%RAML 1.0 NamedExample

value:
-
  Id?: 100
  FirstName?: "Chris"
  LastName? : "Green"
  Email?: "chris@gmail.com"
  Phone?: "123456"
  Description?: "player"
-
  Id?: 101
  FirstName?: "Patrick"
  LastName? : "Jane"
  Email?: "jane@gmail.com"
  Phone?: "987654"
  Description?: "programmer"
